use_frameworks!

platform :ios, '10.0'

target 'MyPascalInterPreter_Example' do
  pod 'MyPascalInterPreter', :path => '../'

  target 'MyPascalInterPreter_Tests' do
    inherit! :search_paths
  end
end
